name: Deploy Vault Server at Hetzner

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Build application
        run: |
          mkdir ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone https://github.com/ackersonde/hetzner_home.git
          cd hetzner_home
          go mod tidy
          go build hetzner.go
          cd ../

          export SERVER_DEPLOY_CACERT_B64=${{ secrets.ORG_SERVER_DEPLOY_CACERT }}
          export SERVER_DEPLOY_SECRET_B64=${{ secrets.ORG_SERVER_DEPLOY_SECRET }}
          export SERVER_DEPLOY_PUBLIC_B64=${{ secrets.ORG_SERVER_DEPLOY_PUBLIC }}
          export SYNCTHING_CONFIG_B64=${{ secrets.ORG_CLOUD_SYNCTHING_CONFIG }}
          export SYNCTHING_KEY=$(echo ${{ secrets.ORG_CLOUD_SYNCTHING_KEY }} | base64 -d)
          export SYNCTHING_CERT=$(echo ${{ secrets.ORG_CLOUD_SYNCTHING_CERT }} | base64 -d)
          export TITAN_PUBLIC_KEY=$(echo ${{ secrets.ORG_TITAN_PUBLIC_KEY }} | base64 -d)
          envsubst '$SERVER_DEPLOY_CACERT_B64, $SERVER_DEPLOY_SECRET_B64, $SERVER_DEPLOY_PUBLIC_B64, $TITAN_PUBLIC_KEY, $SYNCTHING_CONFIG_B64, $SYNCTHING_KEY, $SYNCTHING_CERT' < ./hetzner_home/scripts/raw_ubuntu_userdata.sh >ubuntu_userdata.sh

          export HETZNER_API_TOKEN=$(echo ${{ secrets.ORG_HETZNER_CLOUD_API_TOKEN }} | base64 -d)
          export HETZNER_VAULT_VOLUME_ID=$(echo ${{ secrets.ORG_HETZNER_VAULT_VOLUME_ID }} | base64 -d)
          ./hetzner_home/hetzner -fn=createServer -tag=vault

          # prepare new Hetzner server for Github deployment
          public_ip_address=$(curl -s https://checkip.amazonaws.com)
          source /tmp/new_hetzner_server_params

          ./hetzner_home/hetzner -fn=firewallSSH -tag=vault -ip=$public_ip_address -serverID=$NEW_SERVER_ID

          sudo apt-get -y install nmap
          while [ `nmap "$NEW_SERVER_IPV4" -PN -p ssh | egrep 'open|closed|filtered' | awk '{print $2}'` != "open" ]
          do
            echo "ssh not available..."
            ./hetzner_home/hetzner -fn=checkServer -serverID=$NEW_SERVER_ID
            sleep 3
          done

          export HZ_VOL_MOUNT="/dev/disk/by-id/scsi-0HC_Volume_$HETZNER_VAULT_VOLUME_ID"
          ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_rsa root@$NEW_SERVER_IPV4 "\
            echo 'server executing cloud-init...please be patient'
            cloud-init status --wait > /dev/null 2>&1
            [ $? -ne 0 ] && echo 'Cloud-init failed' && exit 1
            echo 'Cloud-init succeeded at ' `date -R`  > ~/post-cloud-init.log
            mkdir /mnt/hetzner_disk &&
            mount -o discard,defaults $HZ_VOL_MOUNT /mnt/hetzner_disk
            echo '$HZ_VOL_MOUNT /mnt/hetzner_disk ext4 discard,nofail,defaults 0 0' >> /etc/fstab"

          echo "${{ secrets.ORG_TLS_ACKDE_CRT }}" | base64 -d | tee ackde.crt >/dev/null
          echo "${{ secrets.ORG_TLS_ACKDE_KEY }}" | base64 -d | tee ackde.key >/dev/null
          echo "${{ secrets.ORG_TLS_HAUSM_CRT }}" | base64 -d | tee hausm.crt >/dev/null
          echo "${{ secrets.ORG_TLS_HAUSM_KEY }}" | base64 -d | tee hausm.key >/dev/null
          scp *.crt root@$NEW_SERVER_IPV4:/root/traefik/certs/
          scp *.key root@$NEW_SERVER_IPV4:/root/traefik/keys/
          scp ./hetzner_home/scripts/dynamic_conf.yml root@$NEW_SERVER_IPV4:/root/traefik/

          # deploy Traefik to Hetzner
          ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_rsa root@$NEW_SERVER_IPV4 "\
            docker run -d --name ipv6nat --cap-drop ALL --cap-add NET_ADMIN --cap-add NET_RAW --network host --restart unless-stopped -v /var/run/docker.sock:/var/run/docker.sock:ro robbertkl/ipv6nat && \
            docker run -d --name traefik --restart=unless-stopped \
              -v /var/run/docker.sock:/var/run/docker.sock:ro \
              -v /root/traefik/logs:/var/log/traefik/ \
              -v /root/traefik/certs:/certs/ \
              -v /root/traefik/keys:/keys/ \
              -v /root/traefik/dynamic_conf.yml:/dynamic_conf.yml \
              --label='traefik.enable=true' \
              --label='traefik.http.routers.api.entrypoints=web,secure' \
              --label='traefik.http.routers.api.middlewares=http-ratelimit@file,secHeaders@file,api_auth' \
              --label='traefik.http.routers.api.rule=Host(\`mv.ackerson.de\`)' \
              --label='traefik.http.routers.api.service=api@internal' \
              --label='traefik.http.routers.api.tls.domains=mv.ackerson.de' \
              --label='traefik.http.routers.https-redirect.rule=HostRegexp(\`{any:.*}\`)' \
              --label='traefik.http.routers.https-redirect.middlewares=https-redirect@docker' \
              --label='traefik.http.middlewares.https-redirect.redirectscheme.scheme=https' \
              --label='traefik.http.middlewares.https-redirect.redirectscheme.permanent=true' \
              --label='traefik.http.middlewares.https-redirect.redirectscheme.port=443' \
              -p 80:80 -p 443:443 traefik:2.8 \
              --accesslog.filepath=/var/log/traefik/access.log \
              --log.filepath=/var/log/traefik/traefik.log --log.level=WARN \
              --api --providers.docker.exposedByDefault=false --providers.file.filename=/dynamic_conf.yml \
              --entryPoints.web.forwardedHeaders.trustedIPs=172.17.0.1/24,fd00::/80 \
              --entryPoints.secure.forwardedHeaders.trustedIPs=172.17.0.1/24,fd00::/80 \
              --entrypoints.web.address=:80 --entrypoints.secure.address=:443"

          vault_dir_prep="$(cat <<-EOF
            mkdir -p /mnt/hetzner_disk/vault_data/config
            chown -Rf systemd-network:1000 /mnt/hetzner_disk/vault_data
          EOF
          )"
          init_cmd="$(cat <<-EOF
            sleep 3
            if [ ! -d "/mnt/hetzner_disk/vault_data/core" ] ; then
              docker exec -d vault /vault/config/init-vault.sh
            else # if attaching to existing, correct folder permissions and restart
              docker exec -d vault chown -Rf vault:vault /vault
              sleep 3
              docker restart vault
            fi
          EOF
          )"

          ssh root@$NEW_SERVER_IPV4 "$vault_dir_prep"
          scp scripts/local.json scripts/init-vault.sh root@$NEW_SERVER_IPV4:/mnt/hetzner_disk/vault_data/config/
          ssh root@$NEW_SERVER_IPV4 "\
            docker rm -f vault || true && docker pull vault:latest && \
            docker run -d --cap-add=IPC_LOCK --restart=always \
              -v /mnt/hetzner_disk/vault_data:/vault \
              -e VAULT_API_ADDR=http://127.0.0.1:8200 \
              -e VAULT_ADDR=http://127.0.0.1:8200 \
              --label='traefik.enable=true' \
              --label='traefik.http.routers.vault.middlewares=http-ratelimit@file,secHeaders@file' \
              --label='traefik.http.routers.vault.tls.certResolver=letsencrypt' \
              --label='traefik.http.routers.vault.tls.domains=vault.ackerson.de' \
              --label='traefik.http.routers.vault.rule=Host(\`vault.ackerson.de\`)' \
              --name vault vault:latest server && \
            $init_cmd"

          export CTX_DIGITALOCEAN_DROPLET_PROXY_TOKEN=$(echo ${{ secrets.ORG_DIGITALOCEAN_DROPLET_PROXY_TOKEN }} | base64 -d)
          export CTX_DIGITALOCEAN_FIREWALL=$(echo ${{ secrets.ORG_DIGITALOCEAN_FIREWALL }} | base64 -d)
          ./hetzner_home/hetzner -fn=cleanupDeploy -serverID=$NEW_SERVER_ID -tag=vault

          rm ubuntu_userdata.sh *.crt *.key ~/.ssh/* /tmp/new_hetzner_server_params

          export SLACK_NOTIFY_TOKEN=$(echo ${{ secrets.ORG_SLACK_NOTIFICATIONS_TOKEN }} | base64 -d)
          curl -s -o /dev/null -X POST -d token=$SLACK_NOTIFY_TOKEN -d channel=C092UE0H4 \
            -d text="<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|$GITHUB_REPOSITORY @ $GITHUB_RUN_ID>" \
            https://slack.com/api/chat.postMessage
